"""empty message

Revision ID: 3a9f93f92d0e
Revises: 8a204fa5fe6a
Create Date: 2021-04-07 08:58:10.277608

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3a9f93f92d0e'
down_revision = '8a204fa5fe6a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('dog_routes',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('distance', sa.Float(), nullable=False),
    sa.Column('markerList', sa.JSON(), nullable=False),
    sa.Column('markerListOrder', sa.JSON(), nullable=False),
    sa.Column('roundTrip', sa.Boolean(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.add_column('dogActivities', sa.Column('route_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'dogActivities', 'dog_routes', ['route_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'dogActivities', type_='foreignkey')
    op.drop_column('dogActivities', 'route_id')
    op.drop_table('dog_routes')
    # ### end Alembic commands ###
