"""empty message

Revision ID: 6e911522cd70
Revises: f12d275e8604
Create Date: 2021-04-04 15:21:25.424240

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6e911522cd70'
down_revision = 'f12d275e8604'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('dogs', sa.Column('birthday', sa.Date(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('dogs', 'birthday')
    # ### end Alembic commands ###
