"""empty message

Revision ID: 79de38a18702
Revises: ec5d07254927
Create Date: 2021-04-02 13:16:55.466237

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '79de38a18702'
down_revision = 'ec5d07254927'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('dogs', sa.Column('puppy', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('dogs', 'puppy')
    # ### end Alembic commands ###
