"""empty message

Revision ID: 8a204fa5fe6a
Revises: e1acbfd3129c
Create Date: 2021-04-04 17:14:00.731544

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8a204fa5fe6a'
down_revision = 'e1acbfd3129c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('dogActivities', sa.Column('comment', sa.String(length=500), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('dogActivities', 'comment')
    # ### end Alembic commands ###
